"""
Project Atlas configuration.
"""

# Application
ATLAS_VERSION = "0.6.1"
APP_NAME = "Project Atlas"

# Runtime mode
DEVELOPMENT_MODE = True
DEBUG_MODE = True
LOGGING_ENABLED = True

# AI provider
AI_PROVIDER = "anthropic"
CLAUDE_MODEL = "claude-sonnet-4-6"

# Token limits
TITLE_MAX_TOKENS = 500
SCRIPT_MAX_TOKENS = 2500
DESCRIPTION_MAX_TOKENS = 700
TAGS_MAX_TOKENS = 300
QUALITY_MAX_TOKENS = 800
RESEARCH_MAX_TOKENS = 1200

# Budget controls
MAX_RETRIES = 0
RETRY_FAILED_AGENTS = False
GENERATE_MULTIPLE_TITLES = True
TITLE_CANDIDATE_LIMIT = 3

# Quality thresholds
MIN_OVERALL_SCORE = 8.0
MIN_TITLE_SCORE = 8.0
MIN_SCRIPT_SCORE = 8.0
MIN_DESCRIPTION_SCORE = 7.0
MIN_TAGS_SCORE = 7.0